config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :portfolios, except: [:show]
  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'
  
  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  resources :dev_camp_blogs do
  	member do
  		get :toggle_status
  	end
  end

  root to: 'pages#home'  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/placeholder.rb
module Placeholder
	extend ActiveSupport::Concern

	def self.image_generator(height:, width:)
		"https://via.placeholder.com/#{height}x#{width}"
	end
end

app/models/dev_camp_blog.rb
class DevCampBlog < ApplicationRecord
	enum status: { draft: 0, published: 1}
  extend FriendlyId
  friendly_id :title, use: :slugged

  validates_presence_of :title, :body;

  belongs_to :topic
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
	has_many :technologies
	accepts_nested_attributes_for :technologies, 
	                              reject_if: lambda { |attrs| attrs['name'].blank? }

	include Placeholder
	validates_presence_of :title, :body, :main_image, :thumb_image

	def self.angular
		where(subtitle: 'Angular')
	end

	scope :ruby_on_rails_portfolio_itmes, -> { where(subtitle: 'Ruby on Rails') }

	after_initialize :set_defaults

	def set_defaults
		self.main_image ||= Placeholder.image_generator(height: '600', width: '400')
		self.thumb_image ||= Placeholder.image_generator(height: '350', width: '200')

	end
end

app/models/skill.rb
class Skill < ApplicationRecord
	include Placeholder
	validates_presence_of :title, :percent_utilized

	after_initialize :set_defaults

	def set_defaults
		self.badge ||= Placeholder.image_generator(height: '250', width: '250')
	end
end

app/models/technology.rb
class Technology < ApplicationRecord
  belongs_to :portfolio
end

app/models/topic.rb
class Topic < ApplicationRecord
	validates_presence_of :title

	has_many :dev_camp_blogs
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  validates_presence_of :name
  
  def first_name
   self.name.split.first
  end

  def last_name
   self.name.split.last
  end       
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
	include DeviseWhitelist
	include SetSource
	include CurrentUserConcern
	include DefaultPageContent
end

app/controllers/concerns/current_user_concern.rb
module CurrentUserConcern
	extend ActiveSupport::Concern

	def current_user
		super || guest_user
	end

	def guest_user
		OpenStruct.new(name: "Guest User",
		               first_name: "Guest",
		               last_name: "User",
		               email: "guestUsert@example.com"
		               )
	end
end

app/controllers/concerns/default_page_content.rb
module DefaultPageContent
	extend ActiveSupport::Concern

	included do
		before_action :set_title
	end

 	def set_title
		@page_title = "Moana's Portfolio Project"
		@seo_keywords = "Moana Yamanouchi portfolio"
	end
end

app/controllers/concerns/devise_whitelist.rb
module DeviseWhitelist
	extend ActiveSupport::Concern

	included do
		before_action :configure_permitted_parameters, if: :devise_controller?
	end

 	def configure_permitted_parameters
 		devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
 	    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
 	end 
end

app/controllers/concerns/set_source.rb
module SetSource
	extend ActiveSupport::Concern

	included do
		before_action :set_source
	end

	def set_source
		session[:source] = params[:q] if params[:q]
	end
end

app/controllers/dev_camp_blogs_controller.rb
class DevCampBlogsController < ApplicationController
  before_action :set_dev_camp_blog, only: [:show, :edit, :update, :destroy, :toggle_status]
  layout "dev_camp_blogs"

  # GET /dev_camp_blogs
  # GET /dev_camp_blogs.json
  def index
    @dev_camp_blogs = DevCampBlog.all
    @page_title = "Moana's Porfolio Blog"
  end

  # GET /dev_camp_blogs/1
  # GET /dev_camp_blogs/1.json
  def show
    @page_title = @dev_camp_blog.title
    @seo_keywords = @dev_camp_blog.body
  end

  # GET /dev_camp_blogs/new
  def new
    @dev_camp_blog = DevCampBlog.new
  end

  # GET /dev_camp_blogs/1/edit
  def edit
  end

  # POST /dev_camp_blogs
  # POST /dev_camp_blogs.json
  def create
    @dev_camp_blog = DevCampBlog.new(dev_camp_blog_params)

    respond_to do |format|
      if @dev_camp_blog.save
        format.html { redirect_to @dev_camp_blog, notice: 'Dev camp blog was successfully created.' }
        format.json { render :show, status: :created, location: @dev_camp_blog }
      else
        format.html { render :new }
        format.json { render json: @dev_camp_blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dev_camp_blogs/1
  # PATCH/PUT /dev_camp_blogs/1.json
  def update
    respond_to do |format|
      if @dev_camp_blog.update(dev_camp_blog_params)
        format.html { redirect_to @dev_camp_blog, notice: 'Dev camp blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @dev_camp_blog }
      else
        format.html { render :edit }
        format.json { render json: @dev_camp_blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dev_camp_blogs/1
  # DELETE /dev_camp_blogs/1.json
  def destroy
    @dev_camp_blog.destroy
    respond_to do |format|
      format.html { redirect_to dev_camp_blogs_url, notice: 'Dev camp blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

def toggle_status
  if @dev_camp_blog.draft?
    @dev_camp_blog.published! 
  elsif @dev_camp_blog.published?
    @dev_camp_blog.draft!
  end
    redirect_to dev_camp_blogs_url, notice: 'Post status has been updated'
end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dev_camp_blog
      @dev_camp_blog = DevCampBlog.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def dev_camp_blog_params
      params.require(:dev_camp_blog)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  	@posts = DevCampBlog.all
  	@skills = Skill.all
  end

  def about
  end

  def contact
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  layout 'portfolio'
	def index
		@portfolio_items = Portfolio.all
	end

	def angular
		@angular_portfolio_items = Portfolio.angular
	end

	def new
		@portfolio_item = Portfolio.new
		3.times { @portfolio_item.technologies.build }
	end

	 def create
	    @portfolio_item = Portfolio.new(portfolio_params)

	    respond_to do |format|
	      if @portfolio_item.save
	        format.html { redirect_to portfolios_path, notice: 'Your portfolio item is now live.' }
	      else
	        format.html { render :new } end
	    end
	end

	def edit
      @portfolio_item = Portfolio.find(params[:id])
	end

	def update
	@portfolio_item = Portfolio.find(params[:id])
    respond_to do |format|
      if @portfolio_item.update(portfolio_params)
        format.html { redirect_to portfolios_path, notice: 'Your portfolio was successfully updated.' }
      else
        format.html { render :edit }
    end
    end
  end

  def show
  	@portfolio_item = Portfolio.find(params[:id])
  end
 
  def destroy
  	@portfolio_item = Portfolio.find(params[:id])
  	 @portfolio_item.destroy
    respond_to do |format|
      format.html { redirect_to portfolios_url, notice: 'Record was successfully destroyed.' }
    end
  end

  private

  def portfolio_params
  	params.require(:portfolio).permit(:title, 
  									  :subtitle, 
  									  :body,
  									   technologies_attributes: [:name]
  									  )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dev_camp_blogs_helper.rb
module DevCampBlogsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/dev_camp_blogs/_form.html.erb
<%= form_with(model: dev_camp_blog, local: true) do |form| %>
  <% if dev_camp_blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(dev_camp_blog.errors.count, "error") %> prohibited this dev_camp_blog from being saved:</h2>

      <ul>
        <% dev_camp_blog.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/dev_camp_blogs/edit.html.erb
<h1>Editing Dev Camp Blog</h1>

<%= render 'form', dev_camp_blog: @dev_camp_blog %>

<%= link_to 'Show', @dev_camp_blog %> |
<%= link_to 'Back', dev_camp_blogs_path %>

app/views/dev_camp_blogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Dev Camp Blogs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @dev_camp_blogs.each do |dev_camp_blog| %>
      <tr>
        <td><%= dev_camp_blog.title %></td>
        <td><%= dev_camp_blog.body %></td>
        <td><%= link_to dev_camp_blog.status, toggle_status_dev_camp_blog_path(dev_camp_blog) %></td>
        <td><%= link_to 'Show', dev_camp_blog %></td>
        <td><%= link_to 'Edit', edit_dev_camp_blog_path(dev_camp_blog) %></td>
        <td><%= link_to 'Destroy', dev_camp_blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dev Camp Blog', new_dev_camp_blog_path %>

app/views/dev_camp_blogs/new.html.erb
<h1>New Dev Camp Blog</h1>

<%= render 'form', dev_camp_blog: @dev_camp_blog %>

<%= link_to 'Back', dev_camp_blogs_path %>

app/views/dev_camp_blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @dev_camp_blog.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @dev_camp_blog.body %>
</p>

<%= link_to 'Edit', edit_dev_camp_blog_path(@dev_camp_blog) %> |
<%= link_to 'Back', dev_camp_blogs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @page_title %></title>
    <%= csrf_meta_tags %>

    <meta name="keywords" content="<%= @seo_keywords %>"/>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

       <%= render "/shared/nav" %>

       <% if current_user.is_a?(User) %>
       <%= link_to "Logout",  destroy_user_session_path, method: :delete %>
       <% else %>
       <%= link_to "Register", new_user_registration_path %>
       <%= link_to "Login", new_user_session_path %>
       <% end %>
       
    <%= yield %>

    <% if session[:source] %>
      <p>Thanks for visiting me from <%= session[:source] %> </p>
    <% end %>
  </body>
</html>

app/views/layouts/dev_camp_blogs.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @page_title %></title>
    <%= csrf_meta_tags %>

    <meta name="keywords" content="<%= @seo_keywords %>"/>

    <%= stylesheet_link_tag 'dev_camp_blogs', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

       <% if current_user.is_a?(User) %>
       <%= link_to "Logout",  destroy_user_session_path, method: :delete %>
       <% else %>
       <%= link_to "Register", new_user_registration_path %>
       <%= link_to "Login", new_user_session_path %>
       <% end %>
       
    <%= yield %>

    <%= render "/shared/nav" %>

    <% if session[:source] %>
      <p>Thanks for visiting me from <%= session[:source] %> </p>
    <% end %>
  </body>
</html>

app/views/layouts/portfolio.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @page_title %></title>
    <%= csrf_meta_tags %>

    <meta name="keywords" content="<%= @seo_keywords %>"/>

    <%= stylesheet_link_tag 'portfolios', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

       <%= render "/shared/nav" %>

       <% if current_user.is_a?(User) %>
       <%= link_to "Logout",  destroy_user_session_path, method: :delete %>
       <% else %>
       <%= link_to "Register", new_user_registration_path %>
       <%= link_to "Login", new_user_session_path %>
       <% end %>
       
    <%= yield %>

    <% if session[:source] %>
      <p>Thanks for visiting me from <%= session[:source] %> </p>
    <% end %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<h1>Hi, <%= current_user.first_name %> </h1>
<p>Find me in app/views/pages/home.html.erb</p>

<h1>Blog Posts</h1>
<%= @posts.inspect %>

<h1>Skills</h1>
<%= @skills.inspect %>

app/views/portfolios/angular.html.erb
<h1>Angular Portfolio Item</h1>

<%=link_to "Create New Item", new_portfolio_url %>

<% @angular_portfolio_items.each do |portfolio_item| %>
	<p><%=link_to portfolio_item.title, portfolio_show_path(portfolio_item) %></p>
	<p><%=portfolio_item.subtitle %></p>
	<p><%=portfolio_item.body %></p>
	<%= image_tag portfolio_item.thumb_image unless portfolio_item.thumb_image.nil? %>
	<%= link_to "Edit", edit_portfolio_path(portfolio_item)%>
	<%= link_to 'Delete Portfolio Item', portfolio_path(portfolio_item), method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>

app/views/portfolios/edit.html.erb
<h1>Edit this Portfolio Item</h1>

<%= form_for(@portfolio_item) do |f| %>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

 <div class="field">
    <%= f.label :subtitle %>
    <%= f.text_field :subtitle %>
  </div>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/portfolios/index.html.erb
<h1>Portfolio Item</h1>

<%=link_to "Create New Item", new_portfolio_url %>

<% @portfolio_items.each do |portfolio_item| %>
	<p><%=link_to portfolio_item.title, portfolio_show_path(portfolio_item) %></p>
	<p><%=portfolio_item.subtitle %></p>
	<p><%=portfolio_item.body %></p>
	<%= image_tag portfolio_item.thumb_image unless portfolio_item.thumb_image.nil? %>
	<%= link_to "Edit", edit_portfolio_path(portfolio_item)%>
	<%= link_to 'Delete Portfolio Item', portfolio_path(portfolio_item), method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>

app/views/portfolios/new.html.erb
<h1>Create a new Portfolio Item</h1>

<%= form_for(@portfolio_item) do |f| %>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

 <div class="field">
    <%= f.label :subtitle %>
    <%= f.text_field :subtitle %>
  </div>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <ul>
    <%= f.fields_for :technologies do |technology_form| %>
    <li>
      <%= technology_form.label :name %>
      <%= technology_form.text_field :name %>
    </li>
    <% end %>
  </ul>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/portfolios/show.html.erb
<%= image_tag @portfolio_item.main_image %>

<h1><%= @portfolio_item.title %></h1>

<em><%= @portfolio_item.subtitle %></em>

<h2><%= @portfolio_item.body %></h2>

<h2>Technologies Used:</h2>

<% @portfolio_item.technologies.each do |t| %>
<p><%= t.name %></p>
<% end %>

app/views/shared/_nav.html.erb
 <div>
    <div><%= link_to "Home", root_path %></div>
    <div><%= link_to "About Me", about_me_path %></div>
    <div><%= link_to "Contact", contact_path %></div>
    <div><%= link_to "Blog", dev_camp_blogs_path %></div>
    <div><%= link_to "Portfolio", portfolios_path %></div>
</div>